# Generated by Django 4.0.2 on 2022-02-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_vote_ratio_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='reated',
            new_name='created',
        ),
    ]
